name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '10'
      - uses: actions/checkout@v2
      # Add any build steps here. For example:
      - run: sudo apt-get install -y python2
      
      - run: yarn && yarn build
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: deeplydiligent-me
          channelId: live
